# CMake generated Testfile for 
# Source directory: C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit
# Build directory: C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("smoke" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_smoke.exe")
set_tests_properties("smoke" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;118;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("mrp_jjfb" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_mrp_jjfb.exe")
set_tests_properties("mrp_jjfb" PROPERTIES  ENVIRONMENT "GWY_FIXTURE_ROOT=" _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;122;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("cfg36" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_cfg36.exe")
set_tests_properties("cfg36" PROPERTIES  ENVIRONMENT "GWY_FIXTURE_ROOT=" _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;126;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("game_catalog" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_game_catalog.exe")
set_tests_properties("game_catalog" PROPERTIES  ENVIRONMENT "GWY_FIXTURE_ROOT=" _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;130;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("guest_vfs" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_guest_vfs.exe")
set_tests_properties("guest_vfs" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;134;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("launch_descriptor" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_launch_descriptor.exe")
set_tests_properties("launch_descriptor" PROPERTIES  ENVIRONMENT "GWY_FIXTURE_ROOT=" _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;138;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_resolver" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_resolver.exe")
set_tests_properties("ext_resolver" PROPERTIES  ENVIRONMENT "GWY_FIXTURE_ROOT=" _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;142;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("module_registry" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_module_registry.exe")
set_tests_properties("module_registry" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;146;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_loader" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_loader.exe")
set_tests_properties("ext_loader" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;150;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("mrp_member_view" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_mrp_member_view.exe")
set_tests_properties("mrp_member_view" PROPERTIES  ENVIRONMENT "GWY_FIXTURE_ROOT=" _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;154;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("mrp_reg_primary" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_mrp_reg_primary.exe")
set_tests_properties("mrp_reg_primary" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;158;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("package_scope" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_package_scope.exe")
set_tests_properties("package_scope" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;162;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_entry_observe" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_entry_observe.exe")
set_tests_properties("ext_entry_observe" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;166;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_chunk_observe" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_chunk_observe.exe")
set_tests_properties("ext_chunk_observe" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;170;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_object_observe" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_object_observe.exe")
set_tests_properties("ext_object_observe" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;174;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_helper_handoff" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_helper_handoff.exe")
set_tests_properties("ext_helper_handoff" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;178;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_dsm_record_observe" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_dsm_record_observe.exe")
set_tests_properties("ext_dsm_record_observe" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;182;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_module_entry_abi" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_module_entry_abi.exe")
set_tests_properties("ext_module_entry_abi" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;186;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_entry_null_contract" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_entry_null_contract.exe")
set_tests_properties("ext_entry_null_contract" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;190;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_module_data_init" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_module_data_init.exe")
set_tests_properties("ext_module_data_init" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;195;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("module_r9_switch" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_module_r9_switch.exe")
set_tests_properties("module_r9_switch" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;200;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_er_rw_producer" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_er_rw_producer.exe")
set_tests_properties("ext_er_rw_producer" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;205;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_bootstrap_abi" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_bootstrap_abi.exe")
set_tests_properties("ext_bootstrap_abi" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;210;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_callback_frame" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_callback_frame.exe")
set_tests_properties("ext_callback_frame" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;215;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_post_cont_audit" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_post_cont_audit.exe")
set_tests_properties("ext_post_cont_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;220;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_post_cfn_r9_audit" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_post_cfn_r9_audit.exe")
set_tests_properties("ext_post_cfn_r9_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;225;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_p_extchunk_audit" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_p_extchunk_audit.exe")
set_tests_properties("ext_p_extchunk_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;230;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_shell_publication_audit" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_shell_publication_audit.exe")
set_tests_properties("ext_shell_publication_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;235;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_mrpgcmap_entry_order" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_mrpgcmap_entry_order.exe")
set_tests_properties("ext_mrpgcmap_entry_order" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;240;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_entry_abi_cluster_audit" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_entry_abi_cluster_audit.exe")
set_tests_properties("ext_entry_abi_cluster_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;245;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_cfunction_publication_audit" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_cfunction_publication_audit.exe")
set_tests_properties("ext_cfunction_publication_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;250;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_chunk_provider" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_chunk_provider.exe")
set_tests_properties("ext_chunk_provider" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;255;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_er_rw_bind_restore" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_er_rw_bind_restore.exe")
set_tests_properties("ext_er_rw_bind_restore" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;260;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_gwy_startgame_audit" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_gwy_startgame_audit.exe")
set_tests_properties("ext_gwy_startgame_audit" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;265;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("ext_gwy_shell_shim" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_ext_gwy_shell_shim.exe")
set_tests_properties("ext_gwy_shell_shim" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;269;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("platform_identity" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_platform_identity.exe")
set_tests_properties("platform_identity" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;273;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("platform_userinfo" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_platform_userinfo.exe")
set_tests_properties("platform_userinfo" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;277;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("platform_timer" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_platform_timer.exe")
set_tests_properties("platform_timer" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;281;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("platform_send_app_event" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_platform_send_app_event.exe")
set_tests_properties("platform_send_app_event" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;285;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("platform_handler_registry" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_platform_handler_registry.exe")
set_tests_properties("platform_handler_registry" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;289;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("vm_runtime" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_vm_runtime.exe")
set_tests_properties("vm_runtime" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;294;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("guest_memory" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_guest_memory.exe")
set_tests_properties("guest_memory" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;299;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
add_test("vm_file_service" "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/build-i686/test_vm_file_service.exe")
set_tests_properties("vm_file_service" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;303;add_test;C:/Users/24231/Desktop/jjfb_pc_vmrp_bootkit/CMakeLists.txt;0;")
